version: '3.8'

services:
  dbservice:
    container_name: mysql
    image: mysql
    environment:
      - MYSQL_DATABASE=db_kiran_mart
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql

  appservice:
    container_name: kiranmart
    image: kiranmart-demo
    build: .
    depends_on:
      - dbservice
    restart: on-failure
    ports:
      - 9292:8080
    environment:
      - spring-datasource.url=jdbc:mysql://dbservice:3306/db_kiran_mart?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root

volumes:
  db:
